src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: UserRepository::class)]
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")

 * @UniqueEntity(fields="email", message="Cette adresse e-mail est déjà utilisée.")

 */


class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]

    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    #[ORM\Column(length: 255)]
    private ?string $secteur = null;

    #[ORM\Column(length: 255)]
    private ?string $contrat = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_sortie = null;

//    public function __toString(): string
//    {
//        return $this->email;
//    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function hasRole($role){
        $return = false;
        foreach ($this->roles as $roleParcours){
            if($role == $roleParcours){
                $return = true;
            }
        }
        return $return;
    }


    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getSecteur(): ?string
    {
        return $this->secteur;
    }

    public function setSecteur(string $secteur): static
    {
        $this->secteur = $secteur;

        return $this;
    }

    public function getContrat(): ?string
    {
        return $this->contrat;
    }

    public function setContrat(string $contrat): static
    {
        $this->contrat = $contrat;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->date_sortie;
    }

    public function setDateSortie(?\DateTimeInterface $date_sortie): static
    {
        $this->date_sortie = $date_sortie;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;


class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $builder
            ->add('email', EmailType::class,[
                'attr' => [
                'placeholder' => "Veuillez saisir un email",
                ],
            ])

            ->add('plainPassword', PasswordType::class, [
                'mapped' => false,
                'attr' => [
                    'placeholder' => "Veuillez saisir un mot de passe avec 8 caractères, 1 chiffre et 1 lettre",
                    'autocomplete' => 'new-password'],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Length([
                        'min' => 8,
                        'minMessage' => 'Your password should be at least {{ limit }} characters',
                        'max' => 4096,
                    ]),
                    new Regex([
                        'pattern' => '/(?=\S*[a-z])(?=\S*\d)/',
                        'message' => 'Your password should contain at least 1 number and 1 letter',
                    ]),
                ],
            ])

            ->add('nom', TextType::class, [
                "attr" => [
                    'placeholder' => "Veuillez saisir un nom",
                    "class" => "form-control"
                ]
            ])

            ->add('prenom', TextType::class, [
                "attr" => [
                    'placeholder' => "Veuillez saisir un prénom",
                    "class" => "form-control"
                ]
            ])

            ->add('photo', FileType::class, [
                "attr" => [
                    'placeholder' => "Veuillez uploader une photo",
                    "class" => "form-control"
                ],
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/png',
                            'image/jpeg',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid format (png, jpg)',
                    ])
                ],
            ])

            ->add('secteur', ChoiceType::class,[
                "attr" => [
                    'placeholder' => '-- Choisissez un secteur --',
                    'label' => 'Service',
                    "class" => "form-control"
                ],
                'choices' => [
                    'RH' => 'rh',
                    'Informatique' => 'info',
                    'Comptabilité' => 'compta',
                    'Direction' => 'dir',
                ]
            ])

            ->add('contrat', ChoiceType::class,[
                "attr" => [
                    'label' => 'Type de contrat',
                    'placeholder' => '-- Choisissez un type de contrat --',
                    "class" => "form-control"
                ],
                'choices' => [
                    'CDI' => 'cdi',
                    'CDD' => 'cdd',
                    'Interim' => 'interim',
                ]
            ])

            ->add('date_sortie', DateType::class, [
                "attr" => [
                   "class" => "form-control",
                    "id" => "end_date"
                ],
               'label' => 'Date de fin de contrat',
               'required' => false,
               'format' => 'dd-MM-yyyy',
           ]);
           $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
               $user = $event->getData();
               $form = $event->getForm();
               if (isset($user['contrat']) && in_array($user['contrat'], ['CDD', 'Interim'])) {
                   $form->add('date_sortie', DateType::class, [
                       'label' => 'Date de fin de contrat',
                       'required' => false,
                       'format' => 'dd-MM-yyyy'
                   ]);
               };
           });

            // ->add('date_sortie', DateType::class,[
            //     "attr" => [
            //         "class" => "form-control"
            //     ]
            // ])

        // ;

//        ----- tentative n°1 de choix conditionnel CDI/date -----
//        if ('choices' == 'cdi'){
////                $builder->add('date_sortie', disabledType::class, [
//            $builder->add('date_sortie', HiddenType::class, [
//                'disabled' => 'disabled',
//            ]);
//        }

//        ----- tentative n°2 de choix conditionnel CDI/date -----
//        if('choices' =='cdi'){
//            $builder->remove('date_sortie');
//        }

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'csrf_protection'=> true
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use SymfonyCasts\Bundle\VerifyEmail\Exception\VerifyEmailExceptionInterface;


#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('new', name: 'app_user_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_RH')]
    public function new(Request $request, EntityManagerInterface $entityManager,SluggerInterface $slugger, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $photo = $form->get('photo')->getData();
            if(is_null($photo)){
            $error = new FormError("Veuillez uploader une image");
            $form->get('photo')->addError($error);
                }else {
                $originalFilename = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$photo->guessExtension();

                try {
                    $photo->move(
                        $this->getParameter('photo_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    dd($e);
                }

                $form = $form->getData();
                $form->setPhoto($newFilename);

            }


            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);

        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }


    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_RH')]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager,SluggerInterface $slugger, UserPasswordHasherInterface $userPasswordHasher, Filesystem $filesystem): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $photo = $form->get('photo')->getData();
            if(is_null($photo)){
                $error = new FormError("Veuillez uploader une image");
                $form->get('photo')->addError($error);
            }else {
                $originalFilename = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$photo->guessExtension();




                try {
                    $photo->move(
                        $this->getParameter('photo_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    dd($e);
                }
// supprimer l'ancienne image
                $filesystem->remove(['symlink', 'public/uploads/'.$user->getPhoto(), 'activity.log']);
                $form = $form->getData();
//
//                $form->setPhoto($newFilename);
//                je remplace dans user l'ancienne image par la nouvelle
                $user->setPhoto($newFilename);
            }
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }


    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    #[IsGranted('ROLE_RH')]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ces données ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/user/_form.html.twig
{# ----- formulaire perso qui fonctionne  (sauf CDI/date #}
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-success">{{ button_label|default('Valider') }}</button>
{{ form_end(form) }}

{# ----- formulaire avec CDI/date (pas pu tester chez moi car pas symfony) 
{{ form_start(form) }}
    {{ form_row(form.email) }}
    {{ form_row(form.plainPassword) }}
    {{ form_row(form.nom) }}
    {{ form_row(form.prenom) }}
    {{ form_row(form.photo) }}
    {{ form_row(form.secteur) }}

 <div id="contract">
    {{ form_row(form.contrat) }}
    </div>
    <div id="end_date" style="display: none;">
    {{ form_row(form.date_sortie) }}
    </div>
    {{ form_end(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const contractField = document.querySelector('#{{ form.contrat.vars.id }}');
        const endDateField = document.querySelector('#end_date');

        const display_end_date = function () {
            if (contractField.value === 'CDI') {
                endDateField.style.display = 'none';
            } else {
                endDateField.style.display = 'block';
            }
        };

        display_end_date();

        contractField.addEventListener('change', function () {
            display_end_date();
        });
    });
</script>


    {{ form_row(form.contrat) }}
    {{ form_label(form.date_sortie, 'Date de fin de contrat', {'label_attr': {'class': 'd-none lab'}}) }}
    {{ form_widget(form.date_sortie, {'attr': {'class': 'd-none'}}) }}

<button class="btn btn-primary h3 my-3">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}#}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_user_index') }}">Retour</a>


    {% if app.user is not null and app.user.hasRole("ROLE_RH")%}
    {{ include('user/_delete_form.html.twig') }}
    {% endif %}

{#    {{ include('user/_delete_form.html.twig') }}#}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Email</th>
                <th scope="col">Roles</th>
                <th scope="col">Nom</th>
                <th scope="col">Prenom</th>
                <th scope="col">Photo</th>
                <th scope="col">Secteur</th>
                <th scope="col">Contrat</th>
                <th scope="col">Date_sortie</th>
                <th scope="col">actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.prenom }}</td>
{#                <td> <img src="{{ asset('uploads/user/'~user.photo) }}" width="45px" height="45px"></td>#}
{#                {% if user.photo %}#}
                    <td> <img src="{{ asset('uploads/user/'~user.photo) }}" width="45px" height="45px"></td>
{#                {% endif %}#}
                <td>{{ user.secteur }}</td>
                <td>{{ user.contrat }}</td>
                <td>{{ user.dateSortie ? user.dateSortie|date('Y-m-d') : '' }}</td>
                <td>
                    {% if app.user is not null %}
                    <a class=" btn btn-success" href="{{ path('app_user_show', {'id': user.id}) }}">Détail</a>
                    {% endif %}
                    {% if app.user is not null and app.user.hasRole("ROLE_RH")%}
                    <a class=" btn btn-secondary" href="{{ path('app_user_edit', {'id': user.id}) }}">Modifier</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if app.user is not null and app.user.hasRole("ROLE_RH")%}
    <a class=" btn btn-success" href="{{ path('app_user_new') }}">Enregistrer une nouvelle personne</a>
    {% endif %}
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Enregistrer un nouvel employé</h1>

    {{ include('user/_form.html.twig') }}
    
{#    {{ form_start(form) }}#}




{#            {{ form_row(form.email) }}#}
{#            {{ form_row(form.plainPassword) }}#}
{#            {{ form_row(form.nom) }}#}
{#            {{ form_row(form.prenom) }}#}
{#            {{ form_row(form.photo) }}#}
{#            {{ form_row(form.secteur) }}#}
{#            {{ form_row(form.contrat) }}#}
{#    ----- tentative n°3 de choix conditionnel CDI/date ----- #}
{#    {% if user.contrat.value == 'cdd' %}#}
{#            {{ form_row(form.date_sortie) }}#}
{#    {% endif %}#}
{#            {{ form_row(form.valider) }}#}
{#    {{ form_end(form) }}#}

    <a class=" btn btn-warning" href="{{ path('app_user_index') }}">Retour à la liste</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
{#            <tr>#}
{#                <th>Password</th>#}
{#                <td>{{ user.password }}</td>#}
{#            </tr>#}
            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Photo</th>
{#                {% if user.photo is null %}#}
                <td> <img src="{{ asset('uploads/user/'~user.photo) }}" width="45px" height="45px"></td>
{#                {% endif %}#}
            </tr>
            <tr>
                <th>Secteur</th>
                <td>{{ user.secteur }}</td>
            </tr>
            <tr>
                <th>Contrat</th>
                <td>{{ user.contrat }}</td>
            </tr>
            <tr>
                <th>Date_sortie</th>
                <td>{{ user.dateSortie ? user.dateSortie|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a class=" btn btn-success" href="{{ path('app_user_index') }}">Retour à la liste</a>



    {% if app.user is not null and app.user.hasRole("ROLE_RH")%}
        {{ include('user/_delete_form.html.twig') }}
    {% endif %}

{% endblock %}